import Head from 'next/head'
import WithSubnavigation from '@/components/navbar'
import LargeWithLogoCentered from '@/components/footer'
import SplitScreen from '@/components/body'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <WithSubnavigation/>
        <SplitScreen/>
        <LargeWithLogoCentered/>
      </main>
    </>
  )
}
